### PR TITLE
Fix segfault where model id is given in update but actual model is nil. Fixes #43

### LINKED ISSUE #43: Segfault in UpdateHyperParameters
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14c04ee]

goroutine 20 [running]:
github.com/doc-ai/tensorio-models/server.(*server).UpdateModel(0xc0000c12a0, 0x16c7f40, 0xc000270750, 0xc000276340, 0xc0000c12a0, 0xc000270750, 0xc000228ba8)
	/Users/fkautz/src/tensorio-models/server/server.go:100 +0x35e
github.com/doc-ai/tensorio-models/api._Repository_UpdateModel_Handler(0x15c3d20, 0xc0000c12a0, 0x16c7f40, 0xc000270750, 0xc00024c780, 0x0, 0x16c7f40, 0xc000270750, 0xc000274218, 0x7)
	/Users/fkautz/src/tensorio-models/api/repository.pb.go:1654 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000162480, 0x16cd560, 0xc00007ef00, 0xc00036c000, 0xc0001b0090, 0x1abcba0, 0x0, 0x0, 0x0)
	/Users/fkautz/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:972 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc000162480, 0x16cd560, 0xc00007ef00, 0xc00036c000, 0x0)
	/Users/fkautz/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:1252 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000260c0, 0xc000162480, 0x16cd560, 0xc00007ef00, 0xc00036c000)
	/Users/fkautz/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:691 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/fkautz/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:689 +0xa1
```

### PR DESCRIPTION
**Pull request by fkautz**

### CODE REVIEW

**Comment by fkautz** [comment]
Fixes #43

File: server/server.go [hunk 1]
```diff
@@ -88,6 +89,9 @@ func (srv *server) CreateModel(ctx context.Context, req *api.CreateModelRequest)
 func (srv *server) UpdateModel(ctx context.Context, req *api.UpdateModelRequest) (*api.UpdateModelResponse, error) {
 	modelID := req.ModelId
 	model := req.Model
+	if model == nil {
+		return nil, errors.New("model is missing")
```
Comment (brianbhsu) [inline server/server.go]: Not required but you could create a "MissingModelError" and use that here since it seems like this error could be used in other places.

Comment (fkautz) [reply server/server.go]: I've added this to the api package, uses grpc error status.
